name: Build, Test and Deploy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: run unit tests
      run: npm run test:unit
    - name: display softuni username
      run: echo ProgrammerWannaBe
      
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start app in background
      run: npm run start &
    - name: Run UI Tests
      run: npm run test:ui

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
